### ISSUE TITLE
 MySQL数据同步到pgsql  提示：Out of memory

### ISSUE THREAD

**Issue by DavenAaron** [aliyun/rds_dbsync#106]
COPY failed for table "order_log_web": ERROR:  Out of memory  (seg0 172.31.170.152:40000 pid=28918)
DETAIL:  VM protect failed to allocate 3145776 bytes from system, VM Protect 7303 MB available

内存大小该在哪里设置？   谢谢

**Comment by wjzeng** [comment]
这是greenplum segment 内存不足，建议修改 greenplum参数
