### ISSUE TITLE
pgsql2pgsql(GP to GP 过程)  传输原理疑问？ Segment 点对点传输吗？

### ISSUE THREAD

**Issue by Moonlightflower** [aliyun/rds_dbsync#116]
GreenPlum  迁移数据 到 GreenPlum 时，是 Segment 对应 Segment 吗？
还是先从源 GreenPlum 的 master 导出再到 目标GreenPlum 的master 入库？

**Comment by Moonlightflower** [comment]
如果不是的话，gptransfer 或者 gpcopy 更好用些吧？

**Comment by fuhao1991101** [comment]
> 如果不是的话，gptransfer 或者 gpcopy 更好用些吧？

麻烦请教下，直接下载二进制包，配置my.conf就可以执行pgsql2pgsql了么？为什么我报错：
/lib64/libc.so.6: version `GLIBC_2.14' not found

**Comment by wjzeng** [comment]
GreenPlum 迁移数据到 GreenPlum 是不支持增量的，也不建议走 GreenPlum master节点中转数据。建议使用 gptransfer 或者 gpcopy 等工具。
