### ISSUE TITLE
pgsql2pgsql 执行报错 “version `GLIBC_2.14' not found”

### ISSUE THREAD

**Issue by fuhao1991101** [aliyun/rds_dbsync#117]
下载的mysql2pgsql.bin.el7.20171213版本，配置完my.conf后，执行pgsql2pgsql，如下报错
./pgsql2pgsql: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./pgsql2pgsql)
./pgsql2pgsql: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./pgsql2pgsql)
./pgsql2pgsql: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /user/fuhao/mysql2pgsql.bin.el7.20171213/mysql2pgsql.bin.el7.20171213/bin/../lib/libpq.so.5)
貌似，lib缺失包

**Comment by constzl** [comment]
可以升级glibc到2.14版本

**Comment by wjzeng** [comment]
估计是os版本 libc 库不匹配，建议使用 centos 7
