### ISSUE TITLE
请问mysql5.7，greenplum的版本该怎么选

### ISSUE THREAD

**Issue by tangbinbinyes** [aliyun/rds_dbsync#120]
我这里总是报错，看了帖子说是版本的问题，请给我一个能用的最高版本的greenplum的

**Comment by tangbinbinyes** [comment]
我现在用的是greeplum是5.11的，内核是8.3.23，支持全量同步，增量问题就会报错relation "binlog_miner_status" does not exist

**Comment by zhangnew** [comment]
说的应该是 postgres 的版本要大于 9.3，是临时表，不是说Greenplum的版本

**Comment by wjzeng** [comment]
mysql5.7 到 greenplum，需要一个中间数据库做数据清洗，建议使用pgsql 最新的12 release版，最低要求pg9.4.
