### ISSUE TITLE
读取packet报错

### ISSUE THREAD

**Issue by dgqgithub** [aliyun/rds_dbsync#126]
这个报错是指没有权限读MySQL的binlog文件还是在GP上没有什么权限？
![图片](https://user-images.githubusercontent.com/44500323/61128246-fb2be480-a4e3-11e9-970d-754d84f19339.png)

**Comment by yetHandsome** [comment]
没有在主上创建 REPLICATION SLAVE 权限的用户吧

**Comment by wjzeng** [comment]
mysql 权限配置问题，需要提供给连接用户流复制权限。
