### ISSUE TITLE
好像windows中执行mysql2pgsql中提示 “'mysql2pgsql' 不是内部或外部命令，也不是可运行的程序 或批处理文件。”

### ISSUE THREAD

**Issue by mifashion** [aliyun/rds_dbsync#128]
windows执行mysql2pgsql中提示 “'mysql2pgsql' 不是内部或外部命令，也不是可运行的程序 或批处理文件。”

**Comment by wjzeng** [comment]
需要通过源码，在window开发环境编译出windows的可执行二进制。
