### ISSUE TITLE
centos下编译不通过

### ISSUE THREAD

**Issue by briankang** [aliyun/rds_dbsync#16]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -fpic -fpic -DFRONTEND -I./ -I/usr/pgsql-9.4/include -I/gaodun/dist/mysql/include -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o mysql2pgsql.o mysql2pgsql.c
mysql2pgsql.c:256: error: conflicting types for ‘mysql2pgsql_sync_main’
pgsync.h:129: note: previous declaration of ‘mysql2pgsql_sync_main’ was here
make: *** [mysql2pgsql.o] Error 1
[root@test dbsync]# echo $?
2
[root@test dbsync]# gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
[root@test dbsync]# cat /etc/red
redhat-lsb/     redhat-release  redis.conf      
[root@test dbsync]# cat /etc/redhat-release 
CentOS release 6.5 (Final)
[root@test dbsync]# 

# Minimal requriement: Mysql >= 5.6, Pgsql >= 9.3
己满足要求。

**Comment by wjzeng** [comment]
我来看看

**Comment by wjzeng** [comment]
已经修复
