### ISSUE TITLE
有看到基于时间的增量，但这种对于update,delete这种有好办法么？

### ISSUE THREAD

**Issue by briankang** [aliyun/rds_dbsync#17]
我们目前想到，基于mysql2postgresql时，每个表可以提供一个，最后修改时间的字段(eg: lastuptime)。
不知道rds_dbsync对update,delete这类需求，目前支持的怎么样，将来会怎么样进行支持。

**Comment by briankang** [comment]
我的需求补充如下：
1、能否直接能否支持update ,delete开头的语句，长远来看，ddl语句的同步需求也是需要的。
2、目前我们主要的需求场景,是同步一个库的部分表，可以整表同步，如果能做到字段级别的对应更好。
3、尽量让工具做到不需要去修改表结构，来达到以上需求，万不得己再去改。

**Comment by wjzeng** [comment]
收到，后续的实现考虑到这部分。

**Comment by wjzeng** [comment]
支持从 binlog 解析数据的版本即将开发完成，您可以多关注该github的动态。

**Comment by wjzeng** [comment]
mysql2gp 已经支持了基于解析binlog的增量同步，且开放了二进制，欢迎使用。
