### ISSUE TITLE
mysql到greenplum的增量同步时效性

### ISSUE THREAD

**Issue by migto** [aliyun/rds_dbsync#24]
这个工具可以做到多好？我看到描述文档里面是分钟级同步，不知道是在什么样的额压力条件下的测试结果。greenplum的insert,update和delete效率都是比较低的，如果源库的表更新都特别频繁，表也比较大，比如都是百万量级的，那么这个时效性还能够保证吗？会不会出现更新队列阻塞的情况呢？

**Comment by wjzeng** [comment]
mysql2gp 已经支持了基于解析binlog的增量同步，且开放了二进制，欢迎使用。
