### ISSUE TITLE
PostgreSQL迁移PostgreSQL-XL测试

### ISSUE THREAD

**Issue by liuqian1990** [aliyun/rds_dbsync#26]
项目主页 https://github.com/aliyun/rds_dbsync
参考资料 https://yq.aliyun.com/articles/52815

######重点 只支持库对库,支持update delete insert,但不支持没有主键、DDL语句
rds_dbsync经测试能同步rds_dbsync程序启动之前的数据及后面修改的数据

备份表结构,这个时候我们可以修改表结构,所以我们能够对PostgreSQL-XL集群的表做定制化,这步操作需在local des两台机提前做好
/usr/local/pgsql/bin/pg_dump -F p -s --no-privileges --no-tablespaces --no-owner -h 192.168.1.20 -p 5432 -U pgxc pgxc | /usr/local/pgsql/bin/pgxc pgxc -f -

 
rds_dbsync分为三个角色 src local dec

测试
src          192.168.1.20      单台PostgreSQL
local        192.168.1.21      作为rds_dbsync,在数据库内会产生table(db_sync_status,sync_sqls),sequence(db_sync_status_id_seq,sync_sqls_id_seq) 
des          192.168.1.26      为PostgreSQL-XL集群的协调器

 
src机器上必须有以下条件
alter role pgxc replication
postgres.conf 需要修改为
max_wal_senders = 8
max_replication_slots = 8
wal_level = logical

pg_hba.conf 需要修改为
host    all             all             192.168.1.0/24            trust
host    replication     pgxc            192.168.1.0/24            trust

ali扩展,拷贝文件到相应的目录
/usr/local/pgsql/share/ali_decoding.control
/usr/local/pgsql/lib/ali_decoding.so

local机器上配置
[src.pgsql]
connect_string = "host=192.168.1.20 dbname=pgxc port=5432  user=src password=123456"
[local.pgsql]
connect_string = "host=192.168.1.21 dbname=pgxc port=5432  user=local password=123456"
[desc.pgsql]
connect_string = "host=192.168.1.26 dbname=pgxc port=5432  user=des password=123456"
ignore_copy_error_count_each_table = "0"

src 上需要读取权限，local、des上需读写权限

**Comment by wjzeng** [comment]
感谢支持。
