### ISSUE TITLE
关于多库支持

### ISSUE THREAD

**Issue by 18474475** [aliyun/rds_dbsync#28]
目前计划将公司的一些微服务项目下的数据（单mysql实例，多库）汇总到GP里做统计分析，发现好像只支持单库，全量的倒是无所谓，可以一个一个同步完。增量的话比较麻烦，看是否能支持一下。
另：目前copy多个目录来跑不同库的增量同步，使用同一个local pg schema会不会有问题，如果可以的话，先这样克服下也OK。

**Comment by wjzeng** [comment]
可以支持多DB，我列在需求列表里，多谢关注本项目。

**Comment by zhan8610189** [comment]
这个好支持么？什么时候支持啊？

**Comment by wjzeng** [comment]
可以做，你把你的具体需求提到这个issues里吧

**Comment by zhan8610189** [comment]
一个mysql instance 里有两个库：db1（里面有table11, table12，下同）,db2(table21, table22)，可以同时同步到greenplum的方案有：

1. 同一个schema，里面的表: table11, table12, table21, table22
2. 同一个schema，里面的表加库名前缀: db1_table11, db1_table12, db2_table21, db2_table22
3. 同一个greenplum  instance中会产生两个对应的schema: db1(table11, table12), db2(table21,table22)

您看这三个方案，哪个方案更好些？

**Comment by zhan8610189** [comment]
你们是否可以开源增量同步源码？
你们是否可以让咱们一起来开发完善你们这个工程？

**Comment by wjzeng** [comment]
你好
1 我建议mysql的DB映射成PG/GP的schema
这部分设计local pg的架构变更，计划下一步开发
2 代码时间计划开源的，目前使用的中的问题你可以在issues给我提，也可以加我钉钉（156552320037）详聊

**Comment by wjzeng** [comment]
目前的版本，可以通过搭建多套 mysql2gp 环境的方式，支持单个 mysql instance 下多个DB中的数据同步到 pg gp，且目的库不会出现冲突。该需求也有同学提，所以关掉这个重复 issues 。
