### ISSUE TITLE
make的时候报如下错误

### ISSUE THREAD

**Issue by rongxr** [aliyun/rds_dbsync#3]
[root@localhost dbsync]# make
Makefile:33: 警告：覆盖关于目标“clean”的命令
/usr/local/pgsql/lib/postgresql/pgxs/src/makefiles/pgxs.mk:211: 警告：忽略关于目标“clean”的旧命令
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -DMAP_HUGETLB=0x40000 -fpic -fpic -DFRONTEND -I./ -I/usr/local/pgsql/include -I/usr/local/mysql/include/ -I. -I./ -I/usr/local/pgsql/include/postgresql/server -I/usr/local/pgsql/include/postgresql/internal -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o pg_logicaldecode.o pg_logicaldecode.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -DMAP_HUGETLB=0x40000 -fpic -fpic -DFRONTEND -I./ -I/usr/local/pgsql/include -I/usr/local/mysql/include/ -I. -I./ -I/usr/local/pgsql/include/postgresql/server -I/usr/local/pgsql/include/postgresql/internal -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o pqformat.o pqformat.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -DMAP_HUGETLB=0x40000 -fpic -fpic -DFRONTEND -I./ -I/usr/local/pgsql/include -I/usr/local/mysql/include/ -I. -I./ -I/usr/local/pgsql/include/postgresql/server -I/usr/local/pgsql/include/postgresql/internal -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o stringinfo.o stringinfo.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -DMAP_HUGETLB=0x40000 -fpic -fpic -DFRONTEND -I./ -I/usr/local/pgsql/include -I/usr/local/mysql/include/ -I. -I./ -I/usr/local/pgsql/include/postgresql/server -I/usr/local/pgsql/include/postgresql/internal -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o utils.o utils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -DMAP_HUGETLB=0x40000 -fpic -fpic -DFRONTEND -I./ -I/usr/local/pgsql/include -I/usr/local/mysql/include/ -I. -I./ -I/usr/local/pgsql/include/postgresql/server -I/usr/local/pgsql/include/postgresql/internal -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o misc.o misc.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -DMAP_HUGETLB=0x40000 -fpic -fpic -DFRONTEND -I./ -I/usr/local/pgsql/include -I/usr/local/mysql/include/ -I. -I./ -I/usr/local/pgsql/include/postgresql/server -I/usr/local/pgsql/include/postgresql/internal -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o pgsync.o pgsync.c
In file included from pgsync.c:23:
/usr/local/pgsql/include/zlib.h:86: 错误：expected specifier-qualifier-list before ‘z_const’
/usr/local/pgsql/include/zlib.h:1025: 错误：expected declaration specifiers or ‘...’ before ‘z_const’
/usr/local/pgsql/include/zlib.h:1349: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Z_ARG’
/usr/local/pgsql/include/zlib.h:1673: 错误：expected specifier-qualifier-list before ‘z_off64_t’
/usr/local/pgsql/include/zlib.h:1748: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
/usr/local/pgsql/include/zlib.h:1758: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Z_ARG’
make: *** [pgsync.o] 错误 1
[root@localhost dbsync]#

**Comment by rongxr** [comment]
pg版本：
http://get.enterprisedb.com/postgresql/postgresql-9.4.9-1-linux-x64-binaries.tar.gz

**Comment by wjzeng** [comment]
已修复。
