### ISSUE TITLE
从 MySQL中迁移增量数据到 Greenplum报错

### ISSUE THREAD

**Issue by luoxuesihua** [aliyun/rds_dbsync#30]
执行
 ./binlog_miner 
Adding table: auth_role
[miner] table white list:
[miner] 1 auth_role
[miner] table white list end:
[miner] begin dump binlog from mysql-bin.000001 4
[miner] Rotate mysql-bin.000001 0
ROLLBACK;
# [empty]
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLtable copy failed Query 'COPY binlog_data (event,tbname,new_row,old_key) FROM stdin DELIMITERS '	' with csv QUOTE ''''': ERROR:  relation "binlog_data" does not exist
ERROR: Got error reading packet from server: Lost connection to MySQL server during query
[miner] read binlog fail at mysql-bin.000001 3850 old_off 3850 error 1
[miner] begin dump binlog from mysql-bin.000001 3850
worker thread exit, miner exit
[miner] Rotate mysql-bin.000001 0
worker thread exit, miner exit

**Comment by zhan8610189** [comment]
请问一下 binlog_miner 和 binlog_loader 在哪里可以下载？

**Comment by luoxuesihua** [comment]
https://github.com/aliyun/rds_dbsync/releases
![image](https://cloud.githubusercontent.com/assets/20378720/23115602/df48f1ee-f780-11e6-9fe6-acd76eee6141.png)

**Comment by 18474475** [comment]
这个错误是由于需要在ocal中创建一些基础表。文档里没有写出来。
可以让  @wjzeng  列一下吧。

**Comment by wjzeng** [comment]
相关表定义，我下一个版本做到程序里去。

CREATE TABLE binlog_data (
    id bigint NOT NULL,
    event smallint,
    tbname text,
    new_row text,
    old_key text,
    flag smallint
);

CREATE SEQUENCE binlog_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE binlog_data_id_seq OWNED BY binlog_data.id;
ALTER TABLE ONLY binlog_data ALTER COLUMN id SET DEFAULT nextval('binlog_data_id_seq'::regclass);
ALTER TABLE ONLY binlog_data
    ADD CONSTRAINT binlog_data_pkey PRIMARY KEY (id);
CREATE INDEX idx_binlog_data ON binlog_data USING btree (old_key, id DESC);
CREATE INDEX idx_binlog_event ON binlog_data USING btree (id, flag);
CREATE INDEX idx_binlog_for_window ON binlog_data USING btree (tbname, old_key, id DESC);

**Comment by luoxuesihua** [comment]
执行后导入到中间库没问题,但是从中间库导入Greenplum还是报错,报错信息如下:
./binlog_loader 
Adding table: auth_role
target schema set to public
[binlog_loader_main] begin binlog load from 0
[binlog_loader_main] applyid binlog from 0
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'key' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
[loader] can not get table auth_role pk attr name
[master] task 1 has been created, 11 rows from 0 to 11 ready to be load
[binlog_loader_main] thread exit, proc exit

**Comment by wjzeng** [comment]
钉钉联系我，具体分析下。15652320037

**Comment by luoxuesihua** [comment]
报错原因:没有在gp上创建需要同步的表,在gp上创建主键为id的表后,同步成功
在gp上创建表:
CREATE TABLE auth_role (id int4, role_name text, description text, created_time int8, updated_time int8 , PRIMARY KEY ("id")) DISTRIBUTED BY (id)
