### ISSUE TITLE
增量同步时会出现binlog_loader报错

### ISSUE THREAD

**Issue by zhan8610189** [aliyun/rds_dbsync#32]
麻烦帮忙看一下这个是什么原因
[root@ctc bin]# ./binlog_loader 
Adding table: A1
Adding table: A2
target schema is public
NOTICE:  relation "binlog_washer_status" already exists, skipping
NOTICE:  relation "binlog_load_table_status" already exists, skipping
exec CREATE UNIQUE INDEX idx_binlog_load_table_status on binlog_load_table_status(tbname) failed: ERROR:  relation "idx_binlog_load_table_status" already exists

[binlog_loader_main] applyid binlog from 57942
[washer] task 29 is ready to be wash from 40937 to 56699
exec insert into binlog_load_table_status (tbname) values('A2') failed: ERROR:  duplicate key value violates unique constraint "idx_binlog_load_table_status"
DETAIL:  Key (tbname)=(A2) already exists.

exec insert into binlog_load_table_status (tbname) values('A1') failed: ERROR:  duplicate key value violates unique constraint "idx_binlog_load_table_status"
DETAIL:  Key (tbname)=(A1) already exists.

exec CREATE SCHEMA _tmp_dbsync failed: ERROR:  schema "_tmp_dbsync" already exists

exec CREATE SCHEMA _tmp_dbsync failed: ERROR:  schema "_tmp_dbsync" already exists

NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'key' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'key' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
exec create table _tmp_dbsync.A1_old_key(key int8) failed: ERROR:  relation "A1_old_key" already exists

exec create table _tmp_dbsync.A2_old_key(key int8) failed: ERROR:  relation "A2_old_key" already exists

[loader] table A1 pk attr order_detail_id
[loader] table A2 pk attr id
[loader] task 26 step 1 table public.A2 load A2_old_key to remote 29 row complete, cost 53.517 ms
[loader] task 26 step 2 table delete public.A2 0 row use oldkey complete, cost 23.383 ms
COPY failed: ERROR:  invalid input syntax for type timestamp: "1487691227"  (seg0 GP-segment1-ctc-bj-10-254-8-10:40000 pid=31036)
CONTEXT:  COPY A2, line 10, column 8774515
[loader] task 26 run faild
[loader] task 26 step 1 table public.A1 load A1_old_key to remote 137 row complete, cost 148.300 ms
[loader] task 26 step 2 table delete public.A1 125 row use oldkey complete, cost 17.880 ms
COPY failed: ERROR:  duplicate key value violates unique constraint "A1_pkey"  (seg1 GP-segment1-ctc-bj-10-254-8-10:40001 pid=31039)
DETAIL:  Key (order_detail_id)=(11948632) already exists.
CONTEXT:  COPY A1, line 168: "11948632|149042955|698838|白玉180g|1|0|4|0|1|00000000..."
[loader] task 26 run faild
[master] task 33 has been created, 51124 rows from 57942 to 109066 ready to be load
[binlog_loader_main] thread exit, proc exit

**Comment by zhan8610189** [comment]
binlog_loader从local postgres 导到dest gp时出错，报如下错误信息，COPY failed: ERROR:  invalid input syntax for type timestamp: "1488182415"  
经分析，是binlog_miner从mysql导到local gp前，读出来的时间把timestamp字段变成了long型数据，存在local gp的binlog_data库数据为long型数据了，因此报如上错误而无法把该条记录写进dest gp。
这是一个明显的bug。

**Comment by zhan8610189** [comment]
BUG 3.  增量表同步出现copy csv文件格式不对的BUG
[loader] task 38 step 1 table public.A2 load A2_old_key to remote 98 row complete, cost 154.834 ms
[loader] task 38 step 2 table delete public.A2 1 row use oldkey complete, cost 11.548 ms
COPY failed: ERROR:  unterminated CSV quoted field  (seg8 GP-:40000 pid=47977)
CONTEXT:  COPY A2, line 133: "1208693|1473572|106965|Driscoll's蓝莓1|1|0|-1|0|3|000000009.900000000|..."
[loader] task 38 run faild

**Comment by wjzeng** [comment]
1  duplicate key 的问题已确认是BUG，在一个事物中先后delete 和insert 同一个key会触发问题，准备很快修复。
2 第二个问题已经修复
3 第三个问题确认是部分数据类型没有做数据转义，也会很快修复。

**Comment by zhan8610189** [comment]
三个都修复了。谢谢。
