### ISSUE TITLE
增量上传在使用运维时，需要增强和优化的点

### ISSUE THREAD

**Issue by zhan8610189** [aliyun/rds_dbsync#35]
咱们这个项目需要完善的点，现在想到的有这些：
1. 【重要】在增量同步时会遇到一个gp  db 不同的schema有相同的tablename，即有同步不同的库会有相同的表名。这样同步到同一个gp同一个库时会有些元数据冲突：建议在_tmp_sync里面的<tablename>_old_key建议变成<dbname.tablename>_old_key
2. 【重要】为了便于运维，binlog_miner 这个服务应该 定时的告诉我们，它正在读哪个binlog，及binlog的position已经读到哪里了。
3. 针对mysql instance的同步，一个instance里面有多个库，同步到对应的schema中。
4. 【无关重要】binlog_miner输出日志会有一堆null，不影响服务
5. 【可实现，也可以不实现，人工也是可以的】增量是alter，create这些DDL语句估计无法同时更新，如果不实现，建议还是要从binlog语句中解析出来，然后打印输出出来，让使用者可以一眼就能定位问题。
6. 【使用者自己可以开发一个运维脚本】local gp中的binlog_data的历史数据要清理，可以出一个定时脚本

**Comment by wjzeng** [comment]
多谢关注，我们近期修复。

**Comment by wjzeng** [comment]
问题 1 2 5 已修复
问题 3 近期开发
问题 4 6 属于已知问题，近期完善。
