### ISSUE TITLE
mysql2postgresql、dbsync 支持 geometry 类型同步

### ISSUE THREAD

**Issue by winlin** [aliyun/rds_dbsync#38]
mysql2postgresql、dbsync 支持 geometry 类型同步。
我们有geometry类型的字段需要同步到 GP，目前不支持，请帮忙解决下。

数据示意如下：
 `geoloc` geometry DEFAULT NULL COMMENT '空间地图坐标',

select AsText(geoloc) from tblaccountgps limit 10：
POINT(120.84300231933594 33.22600173950195)
POINT(120.84300231933594 46.65599822998047)
POINT(120.90550231933594 33.22600173950195)
POINT(120.90550231933594 46.65599822998047)
POINT(120.96800231933594 33.22600173950195)

**Comment by winlin** [comment]
MYSQL 源 table schema：

/*
Navicat MySQL Data Transfer

Source Server         : membership_drds_dev
Source Server Version : 50629
Source Host           : drds4173avo0e3u3.drds.aliyuncs.com:3306
Source Database       : membership_drds_dev

Target Server Type    : MYSQL
Target Server Version : 50629
File Encoding         : 65001

Date: 2017-03-22 14:43:29
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for tblaccountgps
-- ----------------------------
DROP TABLE IF EXISTS `tblaccountgps`;
CREATE TABLE `tblaccountgps` (
  `sandboxname` varchar(100) DEFAULT 'membership-dev',
  `guid` varchar(32) NOT NULL,
  `oid` int(11) NOT NULL AUTO_INCREMENT,
  `instanceclass` varchar(100) NOT NULL DEFAULT 'tblaccountgps',
  `issueby_domain` varchar(200) DEFAULT '',
  `issueby_id` varchar(32) DEFAULT '',
  `issueby_oid` int(11) DEFAULT '0',
  `issueby_class` varchar(100) DEFAULT '',
  `issueby_type` varchar(40) DEFAULT '',
  `issuetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastmodifytime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `scrapped` int(11) NOT NULL DEFAULT '0',
  `stop` int(11) NOT NULL DEFAULT '0',
  `description` varchar(500) DEFAULT '',
  `account_domain` varchar(200) DEFAULT 'membership-dev.ipaloma.com' COMMENT '人员,来源数据域',
  `account_id` varchar(32) NOT NULL COMMENT '人员,来源数据id',
  `account_oid` int(11) DEFAULT '0' COMMENT '人员,来源数据oid',
  `account_class` varchar(100) DEFAULT 'tblaccount' COMMENT '人员,来源数据表',
  `account_type` varchar(40) DEFAULT 'membership' COMMENT '人员,来源类型',
  `actiontype` varchar(100) DEFAULT '' COMMENT '行为类型',
  `geoloc` geometry DEFAULT NULL COMMENT '空间地图坐标',
  `geohash` varchar(32) DEFAULT '' COMMENT '空间地图坐标哈希值',
  `districthash` varchar(128) DEFAULT '' COMMENT '省-市-县/区',
  `longitude` double DEFAULT '0' COMMENT '经度',
  `latitude` double DEFAULT '0' COMMENT '纬度',
  `antiaddress` varchar(200) DEFAULT '' COMMENT '地址',
  `locatedbynetwork` int(11) DEFAULT '0' COMMENT '基于无线网络定位',
  `radius` double DEFAULT '0' COMMENT '半径',
  `encryptedby` varchar(100) DEFAULT 'wgs84' COMMENT '采集来源',
  `openid` varchar(64) DEFAULT '' COMMENT '微信端openid',
  `addressissue_domain` varchar(200) DEFAULT '' COMMENT 'gps提供方,来源数据域',
  `addressissue_id` varchar(64) DEFAULT '' COMMENT 'gps提供方,来源id',
  `addressissue_oid` int(11) DEFAULT '0' COMMENT 'gps提供方,来源数据oid',
  `addressissue_class` varchar(100) DEFAULT '' COMMENT 'gps提供方,来源数据表',
  `addressissue_type` varchar(40) DEFAULT '' COMMENT 'gps提供方,来源类型',
  PRIMARY KEY (`oid`),
  UNIQUE KEY `autoindex_tblaccountgps_guid_index` (`guid`,`stop`) USING BTREE,
  KEY `ix_tblaccountgps_districthash_aitype` (`districthash`,`addressissue_domain`,`stop`,`account_id`) USING BTREE,
  KEY `ix_tblaccountgps_account_id_aitype` (`account_id`,`addressissue_type`) USING BTREE,
  KEY `ix_tblaccountgps_location` (`longitude`,`latitude`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=2000643 DEFAULT CHARSET=utf8 COMMENT='人员gps表';

**Comment by wjzeng** [comment]
已在1.3版本中支持。

**Comment by wjzeng** [comment]
配置方式：

tab1 : select col1,col2, AsText(gis1) from tab1;
