### ISSUE TITLE
输出日志信息需要优化，容易误导

### ISSUE THREAD

**Issue by winlin** [aliyun/rds_dbsync#39]
比如：
exec CREATE SCHEMA _tmp_dbsync failed: ERROR:  schema "_tmp_dbsync" already exists
exec CREATE SCHEMA _tmp_dbsync failed: ERROR:  schema "_tmp_dbsync" already exists
exec CREATE SCHEMA _tmp_dbsync failed: ERROR:  schema "_tmp_dbsync" already exists

ERROR: Got error reading packet from server: Lost connection to MySQL server during query
[miner] read binlog fail at mysql-bin.000655 12421553 old_off 12421553 error 1
[miner] begin dump binlog from mysql-bin.000655 12421553

**Comment by wjzeng** [comment]
无关日志已经不打印了
