### ISSUE TITLE
dbsync支持原表PK与PG目的表PK不一致

### ISSUE THREAD

**Issue by winlin** [aliyun/rds_dbsync#42]

**Comment by winlin** [comment]
是不是可以改一下 loader_table_list.txt 的格式，分别指定原表和目的表分别使用的PK是哪个。

MYSQL innodb 引擎推荐使用一个和业务不相关的bigint来作为PK，而在GP里面往往使用join的列作为分布列，这两者就会限制 dbsync 的适用场景。

**Comment by wjzeng** [comment]
已支持。
