### ISSUE TITLE
可否添加基于 MariaDB binlog 解析的增量数据同步

### ISSUE THREAD

**Issue by smileawei** [aliyun/rds_dbsync#43]

**Comment by smileawei** [comment]
使用的MariaDB为10.0.30 。mysql2pgsql二进制版本为mysql2pgsql.bin.el6.20170309 

错误如下：
ERROR: Could not find server version: Master reported unrecognized MySQL version '10.0.30-MariaDB'.
ERROR: Got error reading packet from server: Lost connection to MySQL server during query
可否在版本检测的时候 检测到源mysql不是官方测试通过的几个mysql版本的情况下。提示警告并给用户选择是否继续。

**Comment by wjzeng** [comment]
已在1.3版本中已支持。
