### ISSUE TITLE
希望能支持断点续传的问题，让同步自动化就更好了

### ISSUE THREAD

**Issue by hreo-cxl** [aliyun/rds_dbsync#48]
1、有时偶尔需要针对mysql或者Greenplum数据库进行重启操作，这种时候同步是否能继续接上呢？希望任一设备重启过程中中断的同步能继续跟上。
2、还有一个就是ECS可能难以确保不宕机或者需要重启服务器的情况，这种情况下重启完成能否接着上一次的任务继续同步呢？

**Comment by wjzeng** [comment]
20170413 版本已经支持了该特性。

**Comment by hreo-cxl** [comment]
OK，收到。点赞 +1
