### ISSUE TITLE
【功能增强】针对mysql instance的同步，一个instance里面有多个库，同步到对应的schema中。

### ISSUE THREAD

**Issue by zhan8610189** [aliyun/rds_dbsync#50]

**Comment by wjzeng** [comment]
目前的版本，可以通过搭建多套 mysql2gp 环境的方式，支持单个 mysql instance 下多个DB中的数据同步到 pg gp，且目的库不会出现冲突。该需求之前也有同学提 issue ，所以关掉这个重复 issue 。
