### ISSUE TITLE
个人建议——log日志如果加个时间的话就更好了

### ISSUE THREAD

**Issue by hreo-cxl** [aliyun/rds_dbsync#52]
minner.log和loader.log日志有没有考虑在每一行日志前面加个当时执行的时间来记录下呢？这样的话如果发现同步过程中mysql和GP数据不对称也能快速定位到底是哪个时间段发生的，有助于缩短问题排查范围。

**Comment by wjzeng** [comment]
多谢你的建议，我近期做掉。
之前也有同学提相同的需求，我关掉这个重复的。
