### ISSUE TITLE
binlog增量同步，最大同步表数量限制为128个。

### ISSUE THREAD

**Issue by smileawei** [aliyun/rds_dbsync#53]
mysql>>greenplum在进行binlog增量同步的时候。发现程序限制了最大同步表的数量为128。希望能放的大一些。例如 1024

错误如下：
[miner] table white list:
miner table must <= 128

**Comment by wjzeng** [comment]
已在 mysql2pgsql.bin.el6.20170424.tar.gz 中支持

**Comment by wjzeng** [comment]
已经放大到 1024 了。

**Comment by smileawei** [comment]
多谢。
