### ISSUE TITLE
binlogloader对mysql非法日期时间进行null处理

### ISSUE THREAD

**Issue by zhan8610189** [aliyun/rds_dbsync#56]
mysql支持0000-00-00 00:00:00, 1989-00-00等非法日期和时间的支持，但是postgres不支持，因此，需要建议binlogloader对非法的日期时间进行null处理。

**Comment by wjzeng** [comment]
pgsql 对数据正确性的要求比较严格，不支持 ‘0000-00-00 00:00:00’ 这样的时间类型。请在 mysql 里统一设置一遍。
