### ISSUE TITLE
binlog_loader报错，提示找不到表，试了一下，这两个表是在gp里面的，希望提供具体表结构。

### ISSUE THREAD

**Issue by chenrong2010** [aliyun/rds_dbsync#58]
执行 nohup ./binlog_loader 1>loader.log 2>&1 & 后的报错

[binlog_loader_main] begin binlog load from 0
[binlog_loader_main] applyid binlog from 0
exe sql select id, b, e from binlog_washer_status where finish_time isnull order by id limit 1 faild: ERROR:  relation "binlog_washer_status" does not exist
LINE 1: select id, b, e from binlog_washer_status where finish_time ...
                             ^
exe sql select id, apply_id from binlog_load_table_status where tbname like 't5' order by id limit 1 faild: ERROR:  relation "binlog_load_table_status" does not exist
LINE 1: select id, apply_id from binlog_load_table_status where tbna...
                                 ^
[loader] can not find task id for table t5
[binlog_loader_main] thread exit, proc exit

**Comment by chenrong2010** [comment]
自己创好表之后的报错。
[root@mdw bin]# nohup ./binlog_loader 1>loader.log 2>&1 &
[2] 12140
[root@mdw bin]# tail loader.log
nohup: ignoring input
Adding table: t5
target schema is public
mysql_dbname is test
[binlog_loader_main] load_batch 10 row load_batch_gap 10 second
[binlog_loader_main] begin binlog load from 0
[binlog_loader_main] applyid binlog from 0
[loader] can not find task id for table t5
[binlog_loader_main] thread exit, proc exit
[2]+  Exit 1                  nohup ./binlog_loader > loader.log 2>&1
[root@mdw bin]#

**Comment by wjzeng** [comment]
1 请使用最新的版本 2017-04-24 所有的表能自动创建。
2 需要使用有建表权限的用户登录数据库，请配置在 my.cfg 中。

**Comment by chenrong2010** [comment]
1、我使用的，正是04-24日的版本；
2、我的用户，有权限，我的my.cfg文件如下：
[src.pgsql]
connect_string = "host=192.168.1.1 dbname=test port=5432 user=gptest password=123456"

[local.pgsql]  ###临时 greenplum数据库的地址
connect_string = "host=xx.xx.XXX.221 dbname=testdb port=2345  user=gpadmin password=gpadmin"

[desc.pgsql]  ###目的数据库，指要导入的库。
connect_string = "host=xx.xx.xxx..221 dbname=testdb1 port=2345  user=gpadmin password=gpadmin"
target_schema = "public"
ignore_copy_error_count_each_table = "0"

[binlogloader]
loader_table_list = "loader_table_list.txt"
load_batch = 10
load_batch_gap = 10
今天调试还出现这个问题：
[miner] 1 Rotate mysql-bin.000042 0
505 exe sql update binlog_miner_status set binlogfile = 'mysql-bin.000042', position = 878, last_update = now(),binlog_data_id = (select max(id) from binlog_data) returning binlog_data_id faild: ERROR:  The RETURNING clause of the UPDAT    E statement is not supported in this version of Greenplum Database.
506 [miner] load 1 row 26 byte buffer to local pg, cost 25.974 ms, binlog mysql-bin.000042:878, binlog_data_id -1
507 ERROR: Got error reading packet from server: Lost connection to MySQL server during query
508 [miner] binlog dump thread position at mysql-bin.000042 878 old_off 690 code 1

**Comment by chenrong2010** [comment]
已经成功。原因是用greenplum做local.pgsql，版本太低了，不行，要用9.4以上的pgsql才是可以的。
