### ISSUE TITLE
请问，通过命令 ./mysql2pgsql -d 生成的 DLL 没有主外键，如何解决？

### ISSUE THREAD

**Issue by panxiaoan** [aliyun/rds_dbsync#59]
请问，通过命令 ./mysql2pgsql -d 生成的 DLL 没有主外键，如何解决？

**Comment by wjzeng** [comment]
目前 -d 参数提供列名和列数据类型的 SQL 生成，目的是帮助用户减少 DDL 迁移过程中的工作量。
其他相关信息，PK FK 或迁移到 greenplum 之后的数据分布列相关的信息和应用相关，需要用户手动添加。
