### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by mingmingok** [aliyun/rds_dbsync#6]
/usr/bin/ld: cannot find -lxslt
/usr/bin/ld: cannot find -lxml2
/usr/bin/ld: cannot find -lpam
/usr/bin/ld: cannot find -ledit

环境：CentOS Linux release 7.2.1511 (Core)  64位，希望出一版免编译的。

**Comment by wjzeng** [comment]
Minimal requriement: Mysql >= 5.6, Pgsql >= 9.3。
请按照要求下载 MYSQL PG的二进制进行编译，我们准备发布二进制包。
