### ISSUE TITLE
命令 ./mysql2pgsql -d 生成 DLL bug

### ISSUE THREAD

**Issue by panxiaoan** [aliyun/rds_dbsync#60]
mysql bit(1) 字段，到 postgresql 中，竟然变成了 text 类型，希望的是  bool

**Comment by wjzeng** [comment]
bit(1) 数据类型，暂时没有在 pgsql 中有确定的数据类型，建议和 -l -d 参数一起使用，得到文本方式的 ddl SQL，再手动适当调整。
