### ISSUE TITLE
binlog_miner导入速度太慢

### ISSUE THREAD

**Issue by luoxuesihua** [aliyun/rds_dbsync#66]
我一次性同步200多个表的时间,使用binlog_miner 从mysql 导入到postmaster每秒才导入10条数据,怎么提高导入速度啊,需要配置哪些?

**Comment by zhan8610189** [comment]
miner读取binlog速度的确太慢，感觉是1条1条的binlog日志的读。如下，建议优化miner能批量地读取binlog日志。
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.222 ms, binlog mysql-bin.000133:721029816, binlog_data_id 11779154
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 19.446 ms, binlog mysql-bin.000133:721030675, binlog_data_id 11779156
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 1 row 184 byte buffer to local pg, cost 8.037 ms, binlog mysql-bin.000133:721031079, binlog_data_id 11779157
[miner] load 2 row 489 byte buffer to local pg, cost 16.669 ms, binlog mysql-bin.000133:721031938, binlog_data_id 11779159
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 16.604 ms, binlog mysql-bin.000133:721032797, binlog_data_id 11779161
[miner] load 1 row 184 byte buffer to local pg, cost 16.674 ms, binlog mysql-bin.000133:721033201, binlog_data_id 11779162
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.098 ms, binlog mysql-bin.000133:721034060, binlog_data_id 11779164
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 13.774 ms, binlog mysql-bin.000133:721034919, binlog_data_id 11779166
[miner] load 1 row 184 byte buffer to local pg, cost 8.122 ms, binlog mysql-bin.000133:721035323, binlog_data_id 11779167
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.695 ms, binlog mysql-bin.000133:721036182, binlog_data_id 11779169
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 1 row 184 byte buffer to local pg, cost 10.629 ms, binlog mysql-bin.000133:721036586, binlog_data_id 11779170
[miner] load 1 row 184 byte buffer to local pg, cost 8.277 ms, binlog mysql-bin.000133:721036990, binlog_data_id 11779171
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.278 ms, binlog mysql-bin.000133:721037849, binlog_data_id 11779173
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.150 ms, binlog mysql-bin.000133:721038708, binlog_data_id 11779175
[miner] load 1 row 184 byte buffer to local pg, cost 8.145 ms, binlog mysql-bin.000133:721039112, binlog_data_id 11779176
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.158 ms, binlog mysql-bin.000133:721039971, binlog_data_id 11779178
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 30.791 ms, binlog mysql-bin.000133:721040830, binlog_data_id 11779180
NULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.190 ms, binlog mysql-bin.000133:721041689, binlog_data_id 11779182
[miner] load 1 row 184 byte buffer to local pg, cost 10.506 ms, binlog mysql-bin.000133:721042093, binlog_data_id 11779183
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 7.062 ms, binlog mysql-bin.000133:721042952, binlog_data_id 11779185
[miner] load 1 row 184 byte buffer to local pg, cost 16.559 ms, binlog mysql-bin.000133:721043356, binlog_data_id 11779186
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 1 row 184 byte buffer to local pg, cost 8.368 ms, binlog mysql-bin.000133:721043760, binlog_data_id 11779187
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL[miner] load 2 row 489 byte buffer to local pg, cost 8.108 ms, binlog mysql-bin.000133:721044619, binlog_data_id 11779189

**Comment by wjzeng** [comment]
[binlogloader]
load_batch = 1000 // 最少多少数据开启一个同步子任务，越大越快
load_batch_gap = 60 // 最少多少秒开启一个同步子任务，越大越快

这个参数可以根据实际情况设置，用来提高导入性能。
