### ISSUE TITLE
mysql2pgsql无法在目标PG创建表

### ISSUE THREAD

**Issue by lingniao2000** [aliyun/rds_dbsync#69]
你好，我在centos7.3上面下载了二进制包mysql2pgsql.bin.el6.20170516.
配置好了my.cfg，并在目标PG创建好了schema，然后我执行./mysql2pgsql -l loader_table_list.txt -d -n -j 5 -s db_nono

ignore copy error count 0 each table
-- Adding table: youqian_cooperation_log
-- Adding table: zkb_province_threshold

-- Reference commands to create target tables :
---------------

CREATE TABLE IF NOT EXISTS db_nono.youqian_cooperation_log (id int8, type int4, idfa text, ip text, callback text, replay int4, callback_fail int4, is_success int4, status int4, create_time timestamp, update_time timestamp);

CREATE TABLE IF NOT EXISTS db_nono.zkb_province_threshold (id int8, name text, level int4, parent_id int8, limit_people int4, limit_amount int4, enable int4, version int4, create_time timestamp, update_time timestamp, open_bankCode int4, open_apply int4, limit_1m_people int4, limit_1m_amount int4);

---------------

-- Number of tables: 2         

但实际上并没有在目录库创建表，我抓包看通信过程，大概过程就是此工具往目标库连接了一下，然后就退出了，没有任何日志可以看，不知道该怎么排查 。我尝试编译工具源码，很麻烦没有成功

ps: 附件去掉zip后缀即可
[postgres.pcap.zip](https://github.com/aliyun/rds_dbsync/files/1436613/postgres.pcap.zip)

**Comment by lingniao2000** [comment]
已经好了，请忽略

**Comment by liuzhliang** [comment]
怎么解决的？
