### ISSUE TITLE
binlog_loader 启动自动退出

### ISSUE THREAD

**Issue by lingniao2000** [aliyun/rds_dbsync#70]
[my.cfg.txt](https://github.com/aliyun/rds_dbsync/files/1437085/my.cfg.txt)
你好，我的环境是centos7.3 下载的二进制mysql2pgsql.bin.el6.20170516
我要把mysql的表准实时同步到PG里面,现在mysql2pgsql全量同步和miner拉去都是没有问题的,从临时PG里面能查到增量的binlog，但是不能load，启动的进程自动退出.
mysql 版本 5.6.19，PG版本10.10.0（最新）,两张表都有主键
nohup ./binlog_loader 1>loader.log 2>&1 &
Adding table: youqian_cooperation_log
Adding table: zkb_province_threshold
target schema is db_nono
mysql_dbname is db_nono
[binlog_loader_main] load_batch 10 row load_batch_gap 10 second
NOTICE:  relation "binlog_washer_status" already exists, skipping
NOTICE:  relation "binlog_load_table_status" already exists, skipping
[binlog_loader_main] begin binlog load from 0
[binlog_loader_main] applyid binlog from 0
[loader] can not get table zkb_province_threshold index column name
[loader] can not get table youqian_cooperation_log index column name
[binlog_loader_main] thread exit, proc exit 

尝试源码编译dbsync工具，没有成功。

不知道还要如何排查，求大神帮忙

**Comment by wifish** [comment]
1、在目标库手动创建表 zkb_province_threshold 和 table youqian_cooperation_log 并声明主键。
2、如果主键类型为字符串，那么需要在目标库中名称为_tmp_dbsync的schema中将对应的表主键类型由整形更改为字符串。

**Comment by lingniao2000** [comment]
确实如此,是因为我用mysql2pgsql 导出的建表语句在目标库原样执行的，这个语句没有定义主键

非常感谢
