### ISSUE TITLE
Mysql增量数据同步至Greeplum，启动成功，日志正常，但是数据没有复制过来......

### ISSUE THREAD

**Issue by SbloodyS** [aliyun/rds_dbsync#76]
你好，我下载的是二进制包mysql2pgsql.bin.el6.20170413.tar.gz
机器是docker centos6.6镜像
Mysql版本5.6.38-log
Postgresql 版本PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit
Greenplum版本PostgreSQL 8.2.15 (Greenplum Database 4.3.8.1 build 1) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Apr 20 2016 08:08:56

在Mysql 相同表中insert update 数据，在pg binlog_data中能看到数据变更，但是greenplum 相同表中的数据没变化.....请问该如何解决呢？

**Comment by SbloodyS** [comment]
似乎解决了。。。。哈哈哈哈

**Comment by zhonghai2810** [comment]
@SbloodyS 我遇到同样的问题，请问你如何解决的？
