### ISSUE TITLE
mysql2gp 在从Mysql 5.6 增量同步至 Greenplum 4.3.8.1 时出现转换错误。。。

### ISSUE THREAD

**Issue by SbloodyS** [aliyun/rds_dbsync#77]
COPY failed: ERROR:  invalid input syntax for type timestamp: "NULL"

**Comment by wjzeng** [comment]
请，提供详细表结构和重现序列。

**Comment by SbloodyS** [comment]
Mysql表结构为：
CREATE TABLE `qp_order` (
  `orderId` int(11) NOT NULL AUTO_INCREMENT COMMENT '订单Id',
  `orderNo` varchar(20) DEFAULT NULL COMMENT '订单号',
  `userId` bigint(20) NOT NULL COMMENT '用户Id',
  `couponId` int(11) DEFAULT NULL COMMENT '优惠券Id',
  `state` tinyint(4) NOT NULL,
  `memo` varchar(200) DEFAULT NULL ,
  `carBrandNames` varchar(200) DEFAULT NULL ,
  `source` tinyint(4) NOT NULL ,
  `platForm` tinyint(4) NOT NULL ,
  `totalAmount` decimal(10,2) NOT NULL COMMENT '总金额',
  `actualAmount` decimal(10,2) NOT NULL COMMENT '实际应付金额',
  `promoAmount` decimal(10,2) DEFAULT '0.00' COMMENT '优惠券金额',
  `promotionReduceAmount` decimal(10,2) DEFAULT '0.00' COMMENT '促销减了多少金额',
  `name` varchar(20) NOT NULL COMMENT '收货人姓名',
  `mobile` varchar(20) DEFAULT NULL COMMENT '收货人手机号',
  `tel` varchar(20) DEFAULT NULL COMMENT '收货人座机号',
  `countyId` int(11) DEFAULT '0' COMMENT '区县Id',
  `townID` int(11) DEFAULT NULL COMMENT '乡镇Id',
  `cityId` int(11) DEFAULT NULL COMMENT '城市Id',
  `divisionId` int(11) DEFAULT NULL COMMENT '地区Id',
  `address` varchar(200) DEFAULT NULL COMMENT '详细地址',
  `invoiceType` tinyint(4) DEFAULT NULL ,
  `title` varchar(100) DEFAULT NULL COMMENT '发票抬头',
  `invoiceState` tinyint(4) DEFAULT NULL ,
  `invoicedTime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开票时间',
  `taxpayerIdentificationNo` varchar(30) DEFAULT NULL COMMENT '纳税人识别号（增值税发票需要填）',
  `registrationPhone` varchar(20) DEFAULT NULL COMMENT '注册电话（增值税发票需要填）',
  `depositBank` varchar(50) DEFAULT NULL COMMENT '开户行（增值税发票需要填）',
  `bankAccount` varchar(96) DEFAULT NULL COMMENT '银行账户（增值税发票需要填）',
  `registrationAddress` varchar(100) DEFAULT NULL COMMENT '注册地址（增值税发票需要填）',
  `expiredTime` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '订单未付款过期时间',
  `confirmAllTime` timestamp NULL DEFAULT NULL COMMENT '全部配件确认收货时间',
  `determineState` tinyint(4) DEFAULT '0' ,
  `payTime` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `createTime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `updateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `orgId` bigint(20) NOT NULL COMMENT '组织id',
  `publishTime` timestamp NULL DEFAULT NULL COMMENT '订单发布时间',
  `deliveryState` tinyint(4) DEFAULT '0' ,
  `payState` tinyint(4) DEFAULT '0' ,
  `allPricing` tinyint(1) DEFAULT '0' COMMENT '是否全部定价',
  `hasInValidSupplierOrder` tinyint(1) DEFAULT '0' COMMENT '有不合法的供应商订单',
  `hasAcceptedSupplierOrder` tinyint(1) DEFAULT '0' COMMENT '有接受的供应商订单',
  `agentId` bigint(20) DEFAULT '0' COMMENT '所属服务商ID',
  `provinceId` int(11) NOT NULL DEFAULT '0' COMMENT '下单人省份Id',
  `purchaseState` int(11) DEFAULT '0' ,
  `handleUserId` bigint(20) DEFAULT NULL,
  `freightAmount` decimal(10,2) DEFAULT '0.00' COMMENT '运费',
  `stockAmount` decimal(10,2) DEFAULT '0.00' COMMENT '商品总金额',
  `partsFreight` decimal(10,2) DEFAULT NULL COMMENT '配件应收运费',
  `freightCalRecordId` int(11) DEFAULT NULL COMMENT '运费计算记录表Id',
  `commentStatus` tinyint(4) DEFAULT '-1' ,
  PRIMARY KEY (`orderId`),
  UNIQUE KEY `idx_orderNo` (`orderNo`),
  KEY `idx_userId` (`userId`),
  KEY `idx_cityId` (`cityId`),
  KEY `idx_orgid_payTime_state_source_totalAmount_promoAmount` (`orgId`,`payTime`,`state`,`source`,`totalAmount`,`promoAmount`),
  KEY `idx_createtime_state_source_orgid` (`createTime`,`state`,`source`,`orgId`),
  KEY `idx_state_orgid` (`state`,`orgId`),
  KEY `i_source_payTime_state` (`source`,`payTime`,`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

GP表结构为：
CREATE TABLE "stg"."qp_order" (
"orderid" int4 NOT NULL,
"orderno" varchar(20) COLLATE "default",
"userid" int8,
"couponid" int4,
"state" int2,
"memo" varchar(200) COLLATE "default",
"carbrandnames" varchar(200) COLLATE "default",
"source" int2,
"platform" int2,
"totalamount" numeric(10,2),
"actualamount" numeric(10,2),
"promoamount" numeric(10,2),
"promotionreduceamount" numeric(10,2),
"name" varchar(20) COLLATE "default",
"mobile" varchar(20) COLLATE "default",
"tel" varchar(20) COLLATE "default",
"countyid" int4,
"townid" int4,
"cityid" int4,
"divisionid" int4,
"address" varchar(200) COLLATE "default",
"invoicetype" int2,
"title" varchar(100) COLLATE "default",
"invoicestate" int2,
"invoicedtime" timestamp(0),
"taxpayeridentificationno" varchar(30) COLLATE "default",
"registrationphone" varchar(20) COLLATE "default",
"depositbank" varchar(50) COLLATE "default",
"bankaccount" varchar(96) COLLATE "default",
"registrationaddress" varchar(100) COLLATE "default",
"expiredtime" timestamp(0),
"confirmalltime" timestamp(0),
"determinestate" int2,
"paytime" timestamp(0),
"createtime" timestamp(0),
"updatetime" timestamp(0),
"orgid" int8,
"publishtime" timestamp(0),
"deliverystate" int2,
"paystate" int2,
"allpricing" int2,
"hasinvalidsupplierorder" int2,
"hasacceptedsupplierorder" int2,
"agentid" int8,
"provinceid" int4,
"purchasestate" int4,
"handleuserid" int8,
"freightamount" numeric(10,2),
"stockamount" numeric(10,2),
"partsfreight" numeric(10,2),
"freightcalrecordid" int4,
"commentstatus" int2,
CONSTRAINT "qp_order_pkey" PRIMARY KEY ("orderid")
)
WITH (OIDS=FALSE)
;

根据loader.log日志看到这些：
[washer] task 7 is ready to be wash from 277 to 299
[washer] task 7 wash binlog complete from 277 to 299, update row 22, cost 1.591 ms
[loader] task 7 step 1 table stg.qp_order load qp_order_old_key to remote 6 row complete, cost 0.690 ms
[loader] task 7 step 2 table delete stg.qp_order 6 row use oldkey complete, cost 0.480 ms
COPY failed: ERROR:  invalid input syntax for type timestamp: "NULL"
CONTEXT:  COPY qp_order, line 1, column expiredtime: "NULL"
[loader] task 7 run faild
[master] task 8 has been created, 14 rows from 299 to 313 ready to be load


在 binlog_washer_status 中看到
id为299的数据是：1700585||531000281327||0|||5|7|000000081.000000000|000000081.000000000|.000000000|.000000000|'向鹏'|'13431663912'|'13431663912'|1747|440606104|440600|4|'九江镇沙富工业路3号'|1||2|2017-12-13 09:43:46||||||NULL||0||2017-12-13 09:43:47|2017-12-13 09:43:46|274563||0|0|0|0|0|0|19|0||.000000000|000000081.000000000|.000000000|0|-1

id为277的数据是：
1698831|'O1698831'|531000121029|18103825|3|''||0|1|000002645.000000000|000002575.000000000|000000043.000000000|000000027.000000000|'黄'|'13828184186'|''|1688|445202005|445200|0|'广东揭阳市榕城区东山街道东山加油站旁'|-1||0|2017-12-12 16:48:44||||||2017-12-12 17:48:45||0|2017-12-12 17:30:32|2017-12-12 16:48:44|2017-12-13 09:42:45|159238|2017-12-12 16:48:45|2|2|0|0|1|215281|19|0||.000000000|000002645.000000000|000000011.000000000|1306751|-1

请问哪出了问题呢？

**Comment by SbloodyS** [comment]
这个问题我暂时解决了。。。
