### ISSUE TITLE
请问从 MySQL 导入到mysql2pgsql时，最多可以使用多少线程进行数据同步

### ISSUE THREAD

**Issue by yatou0511** [aliyun/rds_dbsync#81]
`./mysql2pgsql -l <tables_list_file> -d -n -j <number of threads> -s <schema of target able>`
上面命令的`<number of threads> `取值最大是多少

**Comment by wjzeng** [comment]
最大的性能是这个值等于要同步的表个数，再大不会有实际的性能提高。

**Comment by wjzeng** [comment]
[binlogloader]
load_batch = 1000   // 最少多少数据开启一个同步子任务，越大越快
load_batch_gap = 60 // 最少多少秒开启一个同步子任务，越大越快

这连个参数可以根据实际情况设置
