### ISSUE TITLE
pgsync.h:58:19: error: mysql.h: No such file or directory

### ISSUE THREAD

**Issue by gh95533** [aliyun/rds_dbsync#91]
在执行make时，报错：
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -fPIC -DFRONTEND -I./ -I/usr/pgsql-9.6/include -I/usr/local/Cellar/mysql/5.7.15/include/mysql -I. -I./ -I/usr/pgsql-9.6/include/server -I/usr/pgsql-9.6/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgsync.o pgsync.c
In file included from pgsync.c:17:
pgsync.h:58:19: error: mysql.h: No such file or directory
make: *** [pgsync.o] Error 1

**Comment by wjzeng** [comment]
你需要
1 安装 mysql 对应版本二进制
2 rds_dbsync 代码中的修改 Makefile 
调整 mysql_install_dir=/usr/local/Cellar/mysql/5.7.15 的值，对应安装二进制的 include 文件夹

**Comment by gh95533** [comment]
谢谢，参考答案已解决
