### ISSUE TITLE
JSON字段问题的解决方法

### ISSUE THREAD

**Issue by aofengli** [aliyun/rds_dbsync#98]
我按照自己的需求解决了这个问题，希望对后来者有帮助。
软件环境：
1. mysql5.7
2. GreenPlum（基于Postgres8.3）
解决办法：
找到源文件 mysql2pgsql.c:
在`#include <unistd.h>`加入以下代码：

```c
#ifndef MYSQL_TYPE_JSON
#define MYSQL_TYPE_JSON 245
#endif
```
 然后在`switch(type)`里加入
```c
// 我把json转成了TEXTOID
case MYSQL_TYPE_JSON:
    appendPQExpBuffer(ddl, "%s %s", field->org_name, "text");
    col_type[i] = TEXTOID;
    break;
```
改完以后按照步骤 文档编译就好了，
可能遇到的坑：
1. make的时候出错，demo.c g++无法编译
解决办法：
打开MakeFile
查看MakeFile中的mysql_install_dir=xxx这一行和pgsql_install_dir=/usr/pgsql-9.6 是否和你的mysql和pgsql的安装路径的配置是否是你的安装路径

**Comment by luckymaosh** [comment]
> 我按照自己的需求解决了这个问题，希望对后来者有帮助。
> 软件环境：
> 
> 1. mysql5.7
> 2. GreenPlum（基于Postgres8.3）
>    解决办法：
>    找到源文件 mysql2pgsql.c:
>    在`#include <unistd.h>`加入以下代码：
> 
> ```c
> #ifndef MYSQL_TYPE_JSON
> #define MYSQL_TYPE_JSON 245
> #endif
> ```
> 
> 然后在`switch(type)`里加入
> 
> ```c
> // 我把json转成了TEXTOID
> case MYSQL_TYPE_JSON:
>     appendPQExpBuffer(ddl, "%s %s", field->org_name, "text");
>     col_type[i] = TEXTOID;
>     break;
> ```
> 
> 改完以后按照步骤 文档编译就好了，
> 可能遇到的坑：
> 
> 1. make的时候出错，demo.c g++无法编译
>    解决办法：
>    打开MakeFile
>    查看MakeFile中的mysql_install_dir=xxx这一行和pgsql_install_dir=/usr/pgsql-9.6 是否和你的mysql和pgsql的安装路径的配置是否是你的安装路径

大神，你有没有编译好的包
